### ISSUE TITLE
Фикс

### ISSUE THREAD

**Issue by Tre1ny** [BromineMC/Assets#1]
### Describe the feature

Фиксите пермишон

### Additional context

Я хочу админку >;(  или опку, а лучше консоль

**Comment by VidTu** [comment]
Perehoches'.

**Comment by VidTu** [comment]
Fixed. (private commit: [d420e6f](https://github.com/BromineMC/Bromine/tree/d420e6f7e4eb5f74a182265c0b993a12b8105af9))
