### ISSUE TITLE
Кит простокрафт

### ISSUE THREAD

**Issue by Tre1ny** [BromineMC/Assets#11]
### Describe the feature

Добавьте кит просто крафта 

### Additional context

Видту

**Comment by Offenderify** [comment]
Кит "просто крафта может варьироваться", прошу приложить скриншоты/видео такого кита или создать такой на сервере, используя редактор своих наборов и сказать мне ник и номер набора.

**Comment by Tre1ny** [comment]
https://i.imgur.com/77gDvP3.png

**Comment by VidTu** [comment]
Added. (no commit)
