### ISSUE TITLE
Система 1.8

### ISSUE THREAD

**Issue by Tre1ny** [BromineMC/Assets#2]
### Describe the feature

Сделайте урон от снежков, яиц, перок и удочку с 1.8 (не обязательно делать физику)

### Additional context

Видту , не смей

**Comment by VidTu** [comment]
Added. (commit: [Bromine/d2839db8ab349b4b1959a89f9d2a5aef2f805cef](https://github.com/BromineMC/Bromine/tree/d2839db8ab349b4b1959a89f9d2a5aef2f805cef))
