### ISSUE TITLE
Лист обновлений на сервер

### ISSUE THREAD

**Issue by Tre1ny** [BromineMC/Assets#4]
### Describe the feature

Добавить предмет, который если взять в руки и нажать пкм откроется меню обновлений , что бы фичами пользовались которые добавляют , ну или хотябы что бы в чате писались новые фичи

### Additional context

Мама

**Comment by Offenderify** [comment]
Не планируется, все обновления [должны быть в Discord](https://discord.gg/8hGbmebbz7).
