### ISSUE TITLE
Броня в стандартных китах

### ISSUE THREAD

**Issue by Tre1ny** [BromineMC/Assets#6]
### Describe the feature

Сделайте в стандартных китах нерушимую броню

### Additional context

Отчим

**Comment by Offenderify** [comment]
В существующих стандартных наборах броня ломается, чтобы дать более _ванильное_ и _привычное по отношению к другим серверам_ ощущение, чем использование неразрушимой брони. По той же причине в наборах используются зелья, а не талисманы.
