### ISSUE TITLE
Кит модерн

### ISSUE THREAD

**Issue by Tre1ny** [BromineMC/Assets#7]
### Describe the bug

Броня в ките модерн без починки, только инструменты и меч , следовательно стоит либо удалить опыт с кита, либо добавить починку

### To Reproduce

1.Мама
2.Папа
3.Отчим
4.Мачеха

### Screenshots/Videos

https://i.imgur.com/EsBSKEa.png

**Comment by VidTu** [comment]
Пофикшено. (no commit: private config)
