### ISSUE TITLE
Редактор китов

### ISSUE THREAD

**Issue by Tre1ny** [BromineMC/Assets#8]
### Describe the feature

Добавить в редактор китов креатив 

### Additional context

?

**Comment by VidTu** [comment]
Технически уже добавлен, но, скорее всего будет для донатеров, так что оставлю этот баг открытым, либо пока не сделаю донат, либо пока не дам всем эту возможность.

**Comment by Offenderify** [comment]
Добавлено, требует права `bromine.kitedit.creative`, возможно в будущем будет у донатеров.
